feat: setup pre-commit hook
renovatebot/pep440 pull request #150
Opened 2022-02-22 11:22 UTC by RahulGautamSingh

## Changes:

- Setup pre-commit hook using husky

## Context:

- Ref : #129

2022-02-23 14:01 UTC, rarkins requested changes

2022-02-23 14:01 UTC, rarkins commented on package.json
> +    "husky": "^7.0.0",
```suggestion
    "husky": "7.0.4",
```

2022-02-23 14:01 UTC, rarkins commented on package.json
> +    "pretty-quick": "3.1.3"
Shouldn't this be in devDependencies?

2022-02-23 14:12 UTC, rarkins approved these changes

2022-02-23 14:13 UTC, rarkins commented on package.json
> +    "pretty-quick": "3.1.3"
```suggestion
    "pretty-quick": "3.1.3",
```

2022-02-23 16:52 UTC, merged

2022-02-23 16:53 UTC, rarkins commented
D'oh. This should have been a chore: not feat:

2022-02-23 17:58 UTC, RahulGautamSingh commented
> D'oh. This should have been a chore: not feat:

Will be careful next time.

2022-02-24 00:12 UTC, viceice commented
@RahulGautamSingh this is not a feature 😉 this change now caused unnecessary release bubbling. So next time only mark as feature if it really changes final package. 🤗